### ISSUE TITLE
August TODO list

### ISSUE THREAD

**Issue by gallexi** [galantlex/tuftscomp#1]
# Lexi's todos: 
- [x] Get back in touch with Lyft rep
- [x] Email the caterer rep
- [x] Fix the website
- [x] Update housing forms & clear old responses
- [x] New check-in system??
- [x] Confirm that we can use our projector

# Isabel's todos: 

- [x] Create FB event
- [x] Confirm officials
- [x] Research table & chair rental

# Unassigned: 
- [x] Decide exactly which and how many volunteers we need
- [x] Decide how we're filming it
- [x] Talk about vendors

**Comment by ijyliao** [comment]
Github won't let me check/idk how, but the facebook event has been created

**Comment by gallexi** [comment]
@iliao01 I added you as a collaborator to this repo!
