### ISSUE TITLE
September TODO

### ISSUE THREAD

**Issue by gallexi** [galantlex/tuftscomp#2]
- [x]  Download current DB to test my app
- [x]  Pay clearance fee
- [x]  Set up new registration
- [x]  Figure out how to let dancers pay online
- [x]  Decide registration dates/structure
- [x]  Decide costs
- [x]  Reach out to Venue Director
- [x]  Get list of judges
- [x]  Email invites
- [x]  Start putting together paperwork
