### ISSUE TITLE
 October TODO

### ISSUE THREAD

**Issue by gallexi** [galantlex/tuftscomp#3]
- [ ]  Tables and chairs
- [x]  Find/setup volunteer trainers
- [x]  Make general volunteer form
- [ ]  Judges' contracts
- [x]  Officials' contracts
- [x]  MHS Paperwork
- [x]  Find out for sure about vendors
- [x]  Finalize Gnomon copy papers
- [ ]  Figure out livestreaming the comp
- [x]  Hire TEMS

**Comment by gallexi** [comment]
Some followups & things that we learned before closing this issue: 
- Tables and chairs ended up not being needed, because MHS actually had a bunch more!
- Judges' contracts: We didn't submit any to Annie/Emilia until pretty late, and that was INCORRECT. In the future, submit any ones we have returned, like, weekly at the absolute least.
- Livestreaming the comp: using someone's (my) phone was like, not an awful idea (though we had to use data because MHS wifi doesn't play nice with FB), but *power* was a huge issue. We ended up improvising by continually swapping out battery packs, but it wasn't great. For next year, pick someone else and DELEGATE this. Make it their whole job, and then let it go.
